### ISSUE TITLE
InfoBox Directive

### ISSUE THREAD

**Issue by AleskiWeb** [Credera/angular-bing-maps#23]
When I am calling the 'infoBox' directive, as a child of the directive 'pushpin' I am getting an error that the the latitude isn't being found, despite having 'data-lat="test.lat"' on the parent pin inside of an ng-repeat.

I followed the example in the examples directory and upon reproduction I can't seem to get it to work. Any ideas?

**Comment by sjmorrow** [comment]
Sorry for the late response, client needs drove us away from angular bing maps for a few weeks. The only difference I see is you are using 'data-lat' instead of 'lat', but I tried changing our examples to use 'data-lat' and everything still worked as expected.

Can you give a more detailed, reproducible example? A plnkr would be perfect.

**Comment by AleskiWeb** [comment]
I think it was user error rather than an issue, feel free to close this off as a none issue I think.
