### ISSUE TITLE
SVG != polygon directive

### ISSUE THREAD

**Issue by patlux** [Credera/angular-bing-maps#40]
Hi,

I using some inline-svg's in my angular project, with your angular plugin for bing maps, I'm getting an error:

```
Controller 'bingMap', required by directive 'polygon', can't be found!
```

How can I fix that?

See: http://www.w3schools.com/svg/svg_polygon.asp

**Comment by sjmorrow** [comment]
This is usually caused by not having a `<bing-map>` element on the page. The Polygon directive is intended to be used to draw a polygon on top of a bing map. The polygon directive must be a descendant of the `<bing-map>` directive, like so:
```html
<bing-map>
    <polygon></polygon>
</bing-map>
```

Take a look at the example provided for the polygon directive for a fully functional use case:
https://github.com/Credera/angular-bing-maps/blob/v0.2.1/example/polygon-directive.html

**Comment by sjmorrow** [comment]
Disregard that. I now see what you were saying originally. It seems angular-bing-maps is conflicting with the polygon element from the SVG spec. We will need to rename our polygon directive to avoid conflicts like this.

As a temporary workaround, you can add the `ng-non-bindable` directive to your SVG polygons to tell Angular to ignore them. See the following angular doc: https://docs.angularjs.org/api/ng/directive/ngNonBindable

I realize this might cause other issues for you, depending on your implementation, so I will make it a priority to rename that directive.
