### ISSUE TITLE
Bing Map causing css issues on page - Is there an iFrame version?

### ISSUE THREAD

**Issue by robertbarfield** [Credera/angular-bing-maps#42]
I'm running into an issue where the Bing Map is causing the Ladda button loader animation to not show up. I looked into the Bing Map object and noticed it's not iFramed and I'm guessing this is creating the issue. Is there a way to iFrame the Bing Map in this directive?

**Comment by sjmorrow** [comment]
It would not be possible for us to provide an iframe wrapper for the bing maps API because iframes remove you from your applications javascript scope, which would also remove you from the angular scope and break the whole paradigm of using a set of angular directives in the first place.

If you need an iframe, your best solution is to create a standalone application for your bing maps component and put that in an iframe in your main application yourself.

Hope that helps.
